[project]
name = "MSUtils"
version = "0.1.1"
description = "Add a short description here"
authors = [{name = "Sanath Keshav", email = "keshav@mib.uni-stuttgart.de"}]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = ["MSUtils"]

[tool.hatch.build.targets.wheel]
include = ["MSUtils"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tool.pixi.pypi-dependencies]
MSUtils = { path = ".", editable = true }

[tool.pixi.tasks]
voronoi = "python MSUtils/voronoi/main.py"


[tool.pixi.dependencies]
numpy = ">=2.0.1,<3"
h5py = ">=3.11.0,<4"
scipy = ">=1.14.0,<2"
matplotlib = ">=3.9.1,<4"
scikit-image = ">=0.24.0,<0.25"
vtk = ">=9.3.1,<10"
plotly = ">=5.23.0,<6"
lxml = ">=5.2.2,<6"
sympy = ">=1.9.0,<2"
jupyter = ">=1.1.1,<2"
pre-commit = ">=4.0.1,<5"
pyvista = ">=0.44.2,<0.45"

[tool.pixi.feature.build.dependencies]
twine = "*"

[tool.pixi.feature.build.pypi-dependencies]
build = "*"

[tool.pixi.feature.build.tasks]
build_exes = {cmd= "rm -r dist; python -m build"}
push_to_pypi = "python -m twine upload --verbose --repository testpypi dist/*"

[tool.pixi.feature.docs.tasks]
build_docs = "sphinx-build -M html docs docs/_build"
push_docs = "bash docs/scripts/update_docs_by_hand.sh"

[tool.pixi.feature.docs.target.win-64.tasks]
push_docs = "powershell docs/scripts/update_docs_by_hand.ps1"

[tool.pixi.feature.test.tasks]
test = "pytest --junitxml=coverage/junit/test-results.xml --cov=MSUtils --cov-report=term --cov-report=xml:coverage/coverage.xml --cov-report=html:coverage/html ; mkdir -p docs/_static/ && cp -r coverage/html/ docs/_static/test_cov/"
lint = "ruff check"
lint_fix = "ruff check --fix"
lint_gh = "ruff check --output-format=github"
lint_docs_gh = "ruff check --select D,D401 --ignore D417 --output-format=github"
format = "ruff format"
format_diff = "ruff format --diff"
typecheck = "mypy MSUtils"
pre-commit-all = "pre-commit run --all-files"
pre-commit-install = "pre-commit install"

[tool.pixi.feature.docs.dependencies]
sphinx = "*"
pydata-sphinx-theme = "*"
sphinxcontrib-mermaid = "*"
nbsphinx = "*"

[tool.pixi.feature.test.dependencies]
pytest = ">=7.0.0,<8"
pytest-cov = "*"
ruff = "*"
mypy = ">=1.11.2,<2"

[tool.pixi.environments]
build = {features = ["build"]}
default = {features = [], solve-group = "default"}
utility = {features = ["test","docs"], solve-group = "default"}

[tool.ruff.lint]
select = [
    # Aparently, standard:
    "E4",
    "E7",
    "E9",
    "F",
    # # pycodestyle
    "E",
    # # Pyflakes
    "F",
    # # pyupgrade
    # "UP",
    # # flake8-bugbear
    "B",
    # # flake8-simplify
    "SIM",
    # # isort
    "I",
    # # Setting for docstrings, explicit in task lint_docs_gh
    # # Pydocstyle
    # "D",
    # # Augment the convention by requiring an imperative mood for all docstrings.
    # "D401",
]

ignore = [
    # Relax the convention by _not_ requiring documentation for every function parameter.
    "D417",
    # Ignore Line to long stuff
    "E501",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
exclude = []
ignore_missing_imports = true
