[project]
name = "MSUtils"
version = "0.1.0"
description = "Add a short description here"
authors = [{name = "Claudius Haag", email = "claudius.haag@mib.uni-stuttgart.de"}]
requires-python = ">= 3.11"
dependencies = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tool.pixi.pypi-dependencies]
MSUtils = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
numpy = ">=2.0.1,<3"
h5py = ">=3.11.0,<4"
scipy = ">=1.14.0,<2"
matplotlib = ">=3.9.1,<4"
scikit-image = ">=0.24.0,<0.25"
vtk = ">=9.3.1,<10"
plotly = ">=5.23.0,<6"
